CREATE TABLE `ngo` (
  `statey` varchar(50) NOT NULL,
  `name` varchar(200) NOT NULL,
  `site` varchar(500) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



INSERT INTO `ngo` (`statey`, `name`, `site`) VALUES
('ANDAMAN & NICOBAR ISLANDS', 'AdityaNatyaAcademy', '31 M.G. Road, Opp. Sun Sea Resort, Middle Point.'),
('ANDAMAN & NICOBAR ISLANDS', 'Andaman Avians Club', 'Room No.2, Arun Market, Dairy Farm Jn Vijay Baugh Road P.O.Junglighat'),
('ANDAMAN & NICOBAR ISLANDS', 'Andaman Mar Thoma Charitable and Educational Society', 'St. Thomas Marthoma Church Complex, Goalghar, Port Blair'),
('ANDAMAN & NICOBAR ISLANDS', ' ANDAMAN NATURE CLUB', 'Dairy Farm, Junglighat'),
('ANDAMAN & NICOBAR ISLANDS', ' ANDAMAN SANSKRITI PARISHAD', 'PROTHRAPUR PORT BLAIRSOUTH AMDAMAN 744105'),
('ANDHRA PRADESH', '3F SWABHIMAAN FOUNDATION', '3F Swabhimaan Foundation Racherla Village Pentapadu (Mandal) West Godavari Dist. Andhrapradesh-534166 Mobil:9951824777'),
('ANDHRA PRADESH', 'A & A EDUCATIONAL AND IT SOLUTIONS', 'PLOT NO. 170, VENKATESWARA COLONY, PADMAVATI NAGAR, VIZIANAGARAM'),
('ANDHRA PRADESH', 'A G R A', '13-2-264 RAMACHANDRA NAGAR ANANTAPUR - 515 001 ANDHRA PRADESH'),
('ANDHRA PRADESH', 'A S N RAJU SOCIETY FOR SOCIAL WELFARE AND RURAL DEVELOPMENT', 'ASN RAJU SOCIETY FOR SOCIAL WELFARE AND RURAL DEVELOPMENT, D.NO: 2-1-50, FLAT NO: 502, SVR TOWERS, JUVVALAPALEM ROAD'),
('TAMIL NADU', '	PANRUTI ONDRUPATTA ILAIGNER KAZHAKAM', '25,KAMARAJ NAGAR'),
('TAMIL NADU', 'SOCIETY OF SISTERS OF PRESENTATION OF BLESSEDVLRGINMARY SOC NO 7', 'Siruvallur Road Perambur Chennai 600011'),
('TAMIL NADU', '(PAZHANI) KIRANUR SANMARGA GURUKULAM', '(PAZHANI)KIRANUR SANMARGA GURUKULAM JOTHIPURAM, KEERANUR'),
('TAMIL NADU', 'A C T Educational And Charitable Trust', 'No.2070, 1st Street, Vasantham Colony,Anna Nagar, Chennai-600040'),
('CHANDIGARH', '	AMRIT CANCER FOUNDATION', '353 SECTOR 44-A'),
('CHANDIGARH', 'Artscapes', 'Artscapes SCO 7 II Floor Sector 30 D'),
('CHANDIGARH', '	Alankartheatrechd', 'H. no -3184 , Housing Board Complex, EWS Society , sector -52 d , chandigarh'),
('CHANDIGARH', 'World NCD Federation', '11, Karuna Sadan, Sector 11, Chandigarh'),
('CHANDIGARH', 'Youth Technical Training Society', 'Room No 13 (GF), Karuna Sadan Building, Sector 11-B'),
('UTTAR PRADESH', 'A & D Educational Social Trust', 'Opposite Gaushala Market, Railway Road Deoband, District Sharanpur U.P'),
('UTTAR PRADESH', 'A P D I TRUST SAMITI', 'Vill- Manikpur, Post- Alipur Khera, Distt- Mainpuri (U.P.) Pin- 205262'),
('UTTAR PRADESH', '	A ONE EDUCATIONAL IMDAADI TRUST', 'NEAR DARGAH AALIYA NAZAF-E-HIND VILL AND POST AHMADPUR SADAT URF JOGIRAMPURI TEHSIL NAJIBABAD'),
('UTTAR PRADESH', 'ABHISHEK EDUCATIONAL SOCIETY', '156, MUZAAR NAGAR (UTTAR PRADESH)'),
('UTTAR PRADESH', 'ABHISHEK GUPTA MEMORIAL EDUCATIONAL AND WELFARE SOCIETY', '3/200 VIKASNAGARLUCKNOWUTTARPRADESH PIN -226022'),
('MAHARASHTRA', 'Living Water Gospel Broadcast', 'NEV BHAVANA 422 SWATANTRYA VEER SAVARKAR MARG PRABHADEVI'),
('MAHARASHTRA', '360 life changer charitable trust', '123/983 MOTILAL NAGAR NO. 1 OPP BEST DEPOT GOREGAON WEST MUMBAI 400104'),
('MAHARASHTRA', 'A H WADIA SARWAJANIK WACHANALAYA', 'Main Road'),
('MAHARASHTRA', '	A I I A.D. BAWLA FEMALE ORPHANAGE', '60, YARI ROAD, VERSOVA, ANDHERI WEST'),
('MAHARASHTRA', '	A J Foundation', 'A J Foundation Flat No 402 Shiv Prakash S no 16/4 Neeta Park Pimple Nilakh Pune'),
('MAHARASHTRA', '	A S AGRI AND AQUA LLP', 'B, NO, 204, GREEN ACRES A WING, VIJAY NAGARIV'),
('MAHARASHTRA', 'A WORLD OF OPPORTUNITY FOUNDATION', 'C-3, Aditya Birla Centre, S. K. Ahire Marg, Worli, Mumbai-400030');